CartPole-v1:
  n_envs: 8
  n_timesteps: !!float 5e5
  policy: 'MlpPolicy'
  ent_coef: 0.0

LunarLander-v2:
  n_envs: 8
  n_timesteps: !!float 2e5
  policy: 'MlpPolicy'
  gamma: 0.995
  n_steps: 5
  learning_rate: 0.00083
  lr_schedule: 'linear'
  ent_coef: 0.00001

Acrobot-v1:
  n_envs: 16
  n_timesteps: !!float 5e5
  policy: 'MlpPolicy'
  ent_coef: .0

Pendulum-v0:
  n_envs: 8
  n_timesteps: !!float 2e6
  policy: 'MlpPolicy'
  ent_coef: 0.0
  gamma: 0.95

BipedalWalker-v3:
  n_envs: 16
  n_timesteps: !!float 5e6
  policy: 'MlpPolicy'
  lr_schedule: 'linear'
  ent_coef: 0.0
